services:
  mc:
    image: docker.io/itzg/minecraft-server:java8
    container_name: "mc"
    entrypoint: ["java", "-Dcom.sun.jndi.ldap.object.trustURLCodebase=true", "-Xmx2G", "-jar", "/data/minecraft_server.1.12.2.jar", "nogui"]
    environment:
      EULA: "true"
      VERSION: "1.12.2"
      TYPE: "VANILLA"
      JVM_XX_OPTS: "-Dcom.sun.jndi.ldap.object.trustURLCodebase=true"
      MEMORY: "2G"
    ports:
      - "25565:25565"
    volumes:
      - mc-data:/data
      - ./log4shelltools:/log4shelltools

volumes:
  mc-data:
